version: "3"

services:
  mysql_db:
    image: mysql:oraclelinux9
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql2005
      - MYSQL_DATABASE=accounts_db
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: